version: 0.2
phases:
    install:
       commands:
           - apt update -y
           - apt install sudo -y
           - apt install ruby-full -y
           - apt install ruby-bundler ruby-dev build-essential zlib1g-dev nodejs -y
           - gem install fast_blank -v '1.0.0'
           - gem install nokogiri -v '1.10.4'
           - gem install bundler -v '2.0.2'
           - gem update --system '2.7.9'
    pre_build:
       commands:
           - echo pre_build         
    build:
       commands:
           - echo Build started on `date`
           - bundle install
           - bundle exec middleman build --clean
           - mv build/**/* ./
           - mv build/* ./
artifacts:
    files:
         - '**/*'
